name: sports
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ## State Management
  provider:
  ## utils
  image_picker:
  file_picker: ^8.0.0+1
  iconsax:
  http:
  flutter_spinkit: ^5.2.0
  intl:
  fluttertoast:
  shared_preferences:
  logger:
  connectivity:
  dob_input_field: ^2.0.0
  country_picker: ^2.0.25
  another_flushbar: ^1.12.30
dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  

# ------------------------ Local Assets --------------------------- #
  assets:
    - assets/images/auth/ 
    - assets/images/modules/ 
    - assets/images/player_organization/
    - assets/images/swimming_organization/


# ------------------------ Local Fonts --------------------------- #

  fonts:
    - family: Poppins
      fonts:
          - asset: assets/fonts/Poppins-Bold.ttf
          - asset: assets/fonts/Poppins-ExtraBold.ttf
          - asset: assets/fonts/Poppins-SemiBold.ttf
          - asset: assets/fonts/Poppins-Medium.ttf
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 700       