// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvFSNEPDCwm6GB6Xq2V_4weCaTvnR2d2k',
    appId: '1:804560731829:android:7850dc62f3373624dec8fc',
    messagingSenderId: '804560731829',
    projectId: 'fir-b1e27',
    databaseURL: 'https://fir-b1e27-default-rtdb.firebaseio.com',
    storageBucket: 'fir-b1e27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWSlC0KCJt6ynpRwWqV5b7-NPIbx5MeyY',
    appId: '1:804560731829:ios:4dc35fe81059e852dec8fc',
    messagingSenderId: '804560731829',
    projectId: 'fir-b1e27',
    databaseURL: 'https://fir-b1e27-default-rtdb.firebaseio.com',
    storageBucket: 'fir-b1e27.appspot.com',
    androidClientId: '804560731829-1gjj1c6p7ih95fmvgbsh1thm455o0337.apps.googleusercontent.com',
    iosClientId: '804560731829-chkfdljq925ro6qcq8s2cs5dllh4j1bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.sports',
  );
}
